@baseUrl=http://localhost:3001/api/auth0

@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiZWt6VmJ3QTlGNTh6dkZNelRLQjhZc00zTmdBTWVTV1RAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImlhdCI6MTY2NjIxMDcyNSwiZXhwIjoxNjY2Mjk3MTI1LCJhenAiOiJla3pWYndBOUY1OHp2Rk16VEtCOFlzTTNOZ0FNZVNXVCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbXX0.hRxqSkgmIpPyhyIcxMNWoVvBqXeRYOAhz0pXOqhc6xLmOY-axul8hog2BjP9OcdEo2G8Yb_f_TTf0tBpn4L_Jw32-LNorL4mILP23Hkp7VTW_Krgek4Jkzex7WBv5l05eEzY-z-HhneE0hjkfcT8tUuoNZV9Fc5JdYlUzSUKdedxmgTEBQEpk4aGoeM2tYqCEbaPxHbBn41NxTbnC6JO2kqu7SRVyc4B0nkY4f9GcFofccrwpABfcPnjZcOl5xc_tqrhibUnMRSj1SsdcosoSV_I2nKlE_7vPmHAlCmqIhqwpGZcqPnvDAU5VZ_nfq5jNFEcTOcLxQksl5_jU19ATw
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###