@baseUrl=http://localhost:3001/api/auth0

@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiZ2l0aHVifDEzMTU1MTIwIiwiYXVkIjpbImh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImh0dHBzOi8vZGV2LXc4cDZuamt1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjYyODc4ODcsImV4cCI6MTY2NjM3NDI4NywiYXpwIjoibjBJRllFRU1tZ3hoeUFtaXRMb2tlWUdWeUhLY3JSU1oiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.cRTUzed2yZBfA7ps2nUCkFMWOd8sdcrdLFL9jcqYKsPrPMIzVGN0iIo7GFy-cgWVr4p7PdletJm9T87ooXnL-zg7BX1ZrKbldpvJljhRUcbxGlPDuLaXg4xk_fMCCEDWk-2TajK9LJ4HbpXvW24RzYK3ikL6VxdzNsebtZwp30K4DYVHoGmXepAwdAquH6ANfGo25cm6qg6OmYYpeIUlILUcQu1UfGewJbLHDzQH87p9xN-JdimJXusf-sxsXh_b-_hk-qYMsP-0YEOgBZn1-iUWIYfAfzNlySHG51UdqQyPha3_BMoma6EaAfFU9NCzas_guaKHADgYrobj5X4F0g
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###