@baseUrl=http://localhost:3001/api/comments

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsImlkIjoxLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2NDIxNDM5NSwiZXhwIjoxNjY0MzAwNzk1fQ.ICOj33aGEN0Mn74svr6An9sGwkzx3rR5NVJHbFxwoBA
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Maybe we should!",
  "authorId": 2,
  "issueId": 2
}

###

PUT {{baseUrl}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "userStory"
}

###

DELETE {{baseUrl}}/3
Authorization: Bearer {{token}}
Content-Type: application/json