@baseUrl=http://localhost:3001/api/issues

@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjM1MDk2MzdkOGJkYWE2MDM0ZmE4ZjkxIiwiYXVkIjpbImh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImh0dHBzOi8vZGV2LXc4cDZuamt1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjYyMjkxMTksImV4cCI6MTY2NjMxNTUxOSwiYXpwIjoibjBJRllFRU1tZ3hoeUFtaXRMb2tlWUdWeUhLY3JSU1oiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.Xci4kWEio3bmJqexqPb9JndYZ_43wY0527_jxzBIyFMmjGtJvv9yhNA8Zp7iRn8AaWz69Hq03mTmtm8-wE4hxntNFGxHJCHkmE2QzbwrhPs5Qw9TXm_Iye1464lTvhxCLlelNyVkBWnkxkpLKNc5AF9XK-rgOwwligbcW9hNWzLZhH7Nb3oKbZ5BdeBrg3fdLJSzgnexztX2cR2nlCEFsW8b6majJ0j0F8bEdKMAB_EpOV9s67Ja8WlcwdYd49ZOr8LkyE3YZk4qS0yjiIExx3iY8vZbm5vhC_ryDb8Y1PJfZSZFwLz24K63WrtrhUlcIIKo2TbaaFcQpiGbFYfuyA
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/backlog
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/21
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "todo",
  "type": "bug",
  "title": "OAuth failure",
  "description": "Google oath not working",
  "assigneeId": 2,
  "sprintId": 1
}

###

PATCH  {{baseUrl}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sprintId": null
}

###

DELETE {{baseUrl}}/21
Authorization: Bearer {{token}}
Content-Type: application/json