@baseUrl=http://localhost:3001/api/issues
###

GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
  "status": "backlog",
  "title": "As Fred, I want to see my data visualized so I can make better decisions.",
  "description": "A test user story",
  "asigneeId": 1,
  "authorId": 1,
  "sprintId": 2
}

###

PUT {{baseUrl}}/1
Content-Type: application/json

{
  "type": "userStory"
}

###

DELETE {{baseUrl}}/3
Content-Type: application/json