@baseUrl=http://localhost:3001/api/memberships

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsImlkIjoxLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2NjEzOTgxOSwiZXhwIjoxNjY2MjI2MjE5fQ.r2UGstiIiCvFVbp_WhqqrNdx4cX1sd7nKRAnlZslRGg
###

GET {{baseUrl}}
Authorization: Bearer {{token}}


###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "3",
  "teamId": "1"
}

###
