@baseUrl=http://localhost:3001/api/projects

@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjM1MThiNzlkOGJkYWE2MDM0ZmE5NWFlIiwiYXVkIjpbImh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImh0dHBzOi8vZGV2LXc4cDZuamt1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjY2MjcwOTEsImV4cCI6MTY2NjcxMzQ5MSwiYXpwIjoibjBJRllFRU1tZ3hoeUFtaXRMb2tlWUdWeUhLY3JSU1oiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.M8wgKIc15Oi9Zd1K9hcpw_MRKq3WafdgO01fyeFsX0-iioKyauZ6pYUeKwpyngqO5T6rCfMTjnbk0HObHZu5_BLuDGCcpbw7kLHQNCnKGypNTX7OTLQyI4SG2UHpcqruGw55xmzWZ_v6CWfuWD0j-A4437u2uw9zlCag1RYqkzR2CtcNkgmHFTpegDYZR_RJbDpWsWbAJr-35_cX-j1K6HaYSO5oyIGkI9pdHxg5keLBY_OcgqUsmhHkmk-Vv_zRQm0XjLpIGeU_nx9YimWi2GK7_v2x__dVIjUkGi_8SZDLd90Gry3rJ1zGgU0Ea5ouAeNeM_JxDz772npgeoFIQQ
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "2026 Business Conference",
  "leadId": "auth0|63518b79d8bdaa6034fa95ae"
}