@baseUrl=http://localhost:3001/api/projects

@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjM1MThiNzlkOGJkYWE2MDM0ZmE5NWFlIiwiYXVkIjpbImh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImh0dHBzOi8vZGV2LXc4cDZuamt1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjYyODkyNTEsImV4cCI6MTY2NjM3NTY1MSwiYXpwIjoibjBJRllFRU1tZ3hoeUFtaXRMb2tlWUdWeUhLY3JSU1oiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.v_bjuIjVzrtNVcTvX9If171AikRdkXqKkEzbJKGPfplh-89Mflsr5kxEc-P9aaXz7Zfjl6gzymzrEPwL4JfUqIG0WYRH_-EsykUSWHN7hj0WyEbXBIN78-JurWgljhmFgdNpcOGwNDS9pYoODBSd8KSjzJOVY8_VGo4gH-_4__Ww97lKKrv5Z_fE2rz9piBnWNXNj800LGS9k8uB0UDMxPoNdsNvb3AZK0In95pFkbmwRhP9tEqmYrdXxdm7R3E6fRvgAM2UehFvrS48QQidbGgMJiu9RwrALblm3vbwYl-62ssYGb6UXQ1v28WfAH1HW8nFR-PnNnMFDKLg4x-Bcw
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "First!",
  "authorId": 1
}