@baseUrl=http://localhost:3001/api/sprints

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsImlkIjoxLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2MzAwNzQ5OCwiZXhwIjoxNjYzMDkzODk4fQ._TJbGKQRlyrQiRZ0l-JKFolMTPpV38eBDa3F-5-FygY

###

GET {{baseUrl}} HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "goal": "Create a minimum usable product.",
  "projectId": 1,
  "authorId": 1
}