@baseUrl=http://localhost:3001/api/sprints

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsImlkIjoxLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2NTk3MDQwNCwiZXhwIjoxNjY2MDU2ODA0fQ.8wsjejp3s-vpppCQ1nwQDTZGjE3BPxO_jzfsfwemUr0

###

GET {{baseUrl}} HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/1
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/board
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "goal": "Create a minimum usable product.",
  "projectId": 1,
  "authorId": 1
}

###

PATCH {{baseUrl}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "active": true
}