@baseUrl=http://localhost:3001/api/users
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsImlkIjoxLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2MzAwNzQ5OCwiZXhwIjoxNjYzMDkzODk4fQ._TJbGKQRlyrQiRZ0l-JKFolMTPpV38eBDa3F-5-FygY

###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###



POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Brad", 
  "lastName": "Bissell", 
  "email": "bb@gmail.com", 
  "password": "secret"
}

###