@baseUrl=http://localhost:3001/api/users
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjM1MThiNzlkOGJkYWE2MDM0ZmE5NWFlIiwiYXVkIjpbImh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImh0dHBzOi8vZGV2LXc4cDZuamt1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjY0OTQ3ODUsImV4cCI6MTY2NjU4MTE4NSwiYXpwIjoibjBJRllFRU1tZ3hoeUFtaXRMb2tlWUdWeUhLY3JSU1oiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.vj-FP3XCUb3kM5JLISOjiir2Zz13qlo-Np0DQs7p8Qv7-Y2q8jK1_t0T-oX3tfLUmtyBcH-78e_c0oFHJnjSINArGLdDArrJFUvdw3UkSwksfJSrkJBeCMKv3qUS1z6W5kvZIde4H6HvCR636Tt5MGF85bVoTBd4OB9SU5ZRR9iQITOX-JKuETZTc3UMP5ziYfK1yyNbfb-rZIuRt5iSxnODPhh7WcEG4Ov3Ma5k0_o-u3UA-h8I-3rbPt9fKpI85P3Cku0BpxB4Zrzy8x4-yYGoEQEKcuRKqOCU91vvASsGEQiPgdVi0Bn6o_s0QXkUJonv2zuGwJV1o7jmarpnsw
@idToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpzQkFmTFF5LUswWjMxM1UxNE1GSCJ9.eyJpc3MiOiJodHRwczovL2Rldi13OHA2bmprdS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjM1MThiNzlkOGJkYWE2MDM0ZmE5NWFlIiwiYXVkIjpbImh0dHBzOi8vc2NydW0tbWFuYWdlbWVudC1iYWNrZW5kLm9ucmVuZGVyLmNvbSIsImh0dHBzOi8vZGV2LXc4cDZuamt1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjY0OTQ3ODUsImV4cCI6MTY2NjU4MTE4NSwiYXpwIjoibjBJRllFRU1tZ3hoeUFtaXRMb2tlWUdWeUhLY3JSU1oiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.vj-FP3XCUb3kM5JLISOjiir2Zz13qlo-Np0DQs7p8Qv7-Y2q8jK1_t0T-oX3tfLUmtyBcH-78e_c0oFHJnjSINArGLdDArrJFUvdw3UkSwksfJSrkJBeCMKv3qUS1z6W5kvZIde4H6HvCR636Tt5MGF85bVoTBd4OB9SU5ZRR9iQITOX-JKuETZTc3UMP5ziYfK1yyNbfb-rZIuRt5iSxnODPhh7WcEG4Ov3Ma5k0_o-u3UA-h8I-3rbPt9fKpI85P3Cku0BpxB4Zrzy8x4-yYGoEQEKcuRKqOCU91vvASsGEQiPgdVi0Bn6o_s0QXkUJonv2zuGwJV1o7jmarpnsw
###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "token": "{{idToken}}"
}

###