@baseUrl=http://localhost:3001/api/users
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsImlkIjoxLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2NjA5OTc1MSwiZXhwIjoxNjY2MTg2MTUxfQ.-JC-Xe4lPYaCmWQae5n_YuROfPTPzwNs4_wEAHZoo8s

###

GET {{baseUrl}}
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Brad", 
  "lastName": "Bissell", 
  "email": "bb@gmail.com", 
  "password": "secret"
}

###